### ISSUE TITLE
add CORE ranking in the calendar [feature request]

### ISSUE THREAD

**Issue by ondrik** [lucjaulmes/core-cfp#1]
Hi Luc,

this calendar is very useful, many thanks for providing it publicly!  Would it be possible to add the CORE ranking to the row next to a conference name (I understand is has been scraped so it already is somewhere in the data)?  That would be quite useful :-).

Best regards,
Ondra

P.S. Note that there is already CORE 2021 ranking

**Comment by lucjaulmes** [comment]
Thanks for the suggestion @ondrik, and glad you like the tool.

I’ve added the rankings to the timeline, with the source of the ranking by hovering the letter grade − those that are not from the latest CORE (like Micro) have a different color.

wikicfp seems to have been down for a week now, so let’s hope it comes back up. If it does I can bump to 2021 ratings easily

**Comment by ondrik** [comment]
Looks perfect, thanks Luc!
